- name: establish route for 10.96.0.0/16
  command: ip route add 10.96.0.0/16 dev eth1 src {{ hostvars[item].ansible_eth1.ipv4.address }}
  with_items: "{{ ansible_hostname }}"

- name: Open port 24007 (GlusterFS daemon)
  firewalld: port=24007/tcp zone=trusted permanent=true state=enabled immediate=true

- name: Open port 24008 (GlusterFS management)
  firewalld: port=24008/tcp zone=trusted permanent=true state=enabled immediate=true

- name: Open port 2222 (GlusterFS sshd)
  firewalld: port=2222/tcp zone=trusted permanent=true state=enabled immediate=true

- name: Open ports 49152-49251 (GlusterFS bricks)
  firewalld: port=49152-49251/tcp zone=trusted permanent=true state=enabled immediate=true

- name: Pull GlusterFS Docker image
  command: docker pull gluster/gluster-centos:latest
  register: task_result
  until: task_result.rc == 0
  retries: 5
  delay: 1

- name: Pull heketi Docker image
  command: docker pull heketi/heketi:dev
  register: task_result
  until: task_result.rc == 0
  retries: 5
  delay: 1

- name: clean up kubernetes /etc directory
  file: path=/etc/kubernetes/manifests state=absent

- name: kubeadm join with master
  command: kubeadm join --token={{ kubernetes_token }} {{ hostvars['master'].ansible_eth1.ipv4.address }}:6443
