apiVersion: v1
kind: ReplicationController
metadata:
  name: heketi
spec:
  replicas: 1
  selector:
    app: heketi
  template:
    metadata:
      name: heketi
      labels:
        app: heketi
    spec:
      hostNetwork: true
      containers:
      - name: heketi
        image: heketi/heketi:dev
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8888
        volumeMounts:
        - name: config
          mountPath: /etc/heketi
        - name: db
          mountPath: /var/lib/heketi
        - name: keys
          mountPath: /usr/share/keys
        # securityContext:
          # privileged: true
          # runAsUser: 1005
          # supplementalGroups: [1005]
      volumes:
        - name: keys
          hostPath:
            path: /usr/share/heketi/keys
        - name: config
          hostPath:
            path: /usr/share/heketi
        - name: db
          glusterfs:
            endpoints: glusterfs-cluster
            path: MyHeketi
